### ISSUE TITLE
Local Setup

### ISSUE THREAD

**Issue by k-arthikm** [techadam/foodie-api#1]
Can you please explain the procedure, how to setup for local using Xamp. Thanks!

**Comment by techadam** [comment]
step 1: clone the repo to your xampp/htdocs folder
step 2: run `php artisan key: generate` in the project folder using command line tool
step 3: create a database in phpmyadmin and update the database credentials in .env file for the project
step 4: run `php artisan migrate` and you should be good to go

**Comment by k-arthikm** [comment]
Thanks!
